apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/djmanu/INENI-PT-gcloud.git
    targetRevision: main
    path: gitops/platform/crossplane-config
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 30
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
